// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCucTx6q_amIlNWMpeCJJKkOvurzD1cZkM',
    appId: '1:762139560841:web:4911836b46cc5502352f58',
    messagingSenderId: '762139560841',
    projectId: 'sistema-de-gestao-de-est-9fcc1',
    authDomain: 'sistema-de-gestao-de-est-9fcc1.firebaseapp.com',
    storageBucket: 'sistema-de-gestao-de-est-9fcc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYJWlfHa-aqsT5dhOtSQw2QJgpQo_LBgI',
    appId: '1:762139560841:android:0ee56e582f8e4353352f58',
    messagingSenderId: '762139560841',
    projectId: 'sistema-de-gestao-de-est-9fcc1',
    storageBucket: 'sistema-de-gestao-de-est-9fcc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKvEyRJi4iteSNkpZjj9tULRaygPCGlII',
    appId: '1:762139560841:ios:489727edaeda76c6352f58',
    messagingSenderId: '762139560841',
    projectId: 'sistema-de-gestao-de-est-9fcc1',
    storageBucket: 'sistema-de-gestao-de-est-9fcc1.appspot.com',
    iosBundleId: 'com.example.gestaoDeEstoque2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKvEyRJi4iteSNkpZjj9tULRaygPCGlII',
    appId: '1:762139560841:ios:489727edaeda76c6352f58',
    messagingSenderId: '762139560841',
    projectId: 'sistema-de-gestao-de-est-9fcc1',
    storageBucket: 'sistema-de-gestao-de-est-9fcc1.appspot.com',
    iosBundleId: 'com.example.gestaoDeEstoque2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCucTx6q_amIlNWMpeCJJKkOvurzD1cZkM',
    appId: '1:762139560841:web:e42aa1817e05387c352f58',
    messagingSenderId: '762139560841',
    projectId: 'sistema-de-gestao-de-est-9fcc1',
    authDomain: 'sistema-de-gestao-de-est-9fcc1.firebaseapp.com',
    storageBucket: 'sistema-de-gestao-de-est-9fcc1.appspot.com',
  );
}
